apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-require-signature.yaml
  - 01-require-provenance.yaml
  - 02-require-sbom-attestation.yaml
  - 03-block-critical-cves.yaml

patches:
  - target:
      kind: ClusterPolicy
    patch: |-
      - op: replace
        path: /spec/validationFailureAction
        value: Audit
